name: Pipeline CI/CD

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  verify_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Test script
        run: echo "Running tests (placeholder)..."